#!/bin/bash

ICONS='Tela'
THEME='Layan-light-Solid'
FONT='MonacoB Nerd Font,  10'
SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes(){
	${SCHEMA} icon-theme "$ICONS"
	${SCHEMA} gtk-theme "$THEME"
	${SCHEMA} font-name "$FONT"
}

apply_themes
