import = ["/home/lcg/.config/hypr/term/alacritty/colors.toml", "/home/lcg/.config/hypr/term/alacritty/fonts.toml"]
live_config_reload = true

[cursor.style]
blinking = "Off"
shape = "Block"

[window]
opacity = 1.0

