[colors.bright]
black = "#909298"
blue = "#A17886"
cyan = "#E09997"
green = "#316F85"
magenta = "#738BAC"
red = "#E4887B"
white = "#cfd1da"
yellow = "#677491"

[colors.cursor]
cursor = "#cfd1da"
text = "#121015"

[colors.dim]
black = "#909298"
blue = "#A17886"
cyan = "#E09997"
green = "#316F85"
magenta = "#738BAC"
red = "#E4887B"
white = "#cfd1da"
yellow = "#677491"

[colors.normal]
black = "#121015"
blue = "#A17886"
cyan = "#E09997"
green = "#316F85"
magenta = "#738BAC"
red = "#E4887B"
white = "#cfd1da"
yellow = "#677491"

[colors.primary]
background = "#121015"
bright_foreground = "#cfd1da"
dim_foreground = "#cfd1da"
foreground = "#cfd1da"

[colors.search.focused_match]
background = "#316F85"
foreground = "#121015"

[colors.search.matches]
background = "#909298"
foreground = "#121015"

[colors.selection]
background = "#677491"
text = "#121015"

[colors.vi_mode_cursor]
cursor = "#316F85"
text = "#121015"
